# Enables extra verbose logging with debug information
debug_log: true

modules:
  # Status updater module that will query your server and post that information on discord
  status_updates_enabled: true
  # DOOC (Discord OOC) module, listens to messages in the ooc channel and relays them to the game
  dooc_enabled: true
  # BYOND account verification module, manages the channel and interactions, requires database connection
  byond_verification_enabled: true
  # Ahelp module, listens to messages in the ahelp channel and uses reply system to allow discord responses
  ahelp_enabled: true
  # Metrics module records statistics about the server into the common database at regular intervals
  metrics_enabled: true
  # Webhooks are used to receive events from the game and act on them, mainly relay them to discord
  webhooks:
    # Global switch for webhook handling, all webhooks endpoints will only work if this is enabled
    enabled: true
    # Network port on which webhooks server will be listening for the requests
    port: 14081
    # OOC webhook, accepts "ooc" type requests from the game and relays them to the ooc channel in discord
    ooc_messages_enabled: true
    # Ahelp webhook, accepts "ahelp" type requests from the game and relays them to the ahelp channel in discord
    ahelp_messages_enabled: true

ss13:
  # The main address of the ss13 server that this bot will communicate with
  server_address: "zeroonyx.rufuszero.com:14076"
  # The access key that incoming requests will be checked against
  # must match the key that is set on your ss13 server in webhook config, can be any string
  access_key: "<your key here>"

discord:
  # Bot token of your discord application
  # Create your bot and find its token here https://discord.com/developers/applications
  bot_token: "<your token here>"
  # Discord channel where status updates will be posted
  status_channel_id: "1283679676895858750"
  # Discord channel where OOC messages will be posted and DOOC messages will be accepted
  ooc_channel_id: "1283485860968534066"
  # Discord channel holding the BYOND verification instructions and interaction components
  byond_verification_channel_id: "1287044820392611953"
  # Ahelp channel for admins to view the in-game ahelp communication and respond to ahelps with simple messages
  ahelp_channel_id: "1292400604282359808"

# Credentials of the main game database, correct `verification` and `player_discord` tables must be preset
database:
  username: "root"
  password: "pass"
  address: "127.0.0.1"
  port: "3306"
  database_name: "onyxdb"
