# Bot token of your discord application
# Create your bot and find its token here https://discord.com/developers/applications
discord_bot_token: "<your token here>"

# The main address of the ss13 server that this bot will communicate with
ss13_server_address: "zeroonyx.rufuszero.com:14076"

# Enables extra verbose logging with debug information
debug_log: true

modules:
  status_updates:
    enabled: true
    # ID of the Discord channel where status updates will be posted
    discord_channel_id: "1283679676895858750"
  webhooks:
    enabled: true
    port: 14081
    # The access key that your ss13 server uses to authenticate incoming and outgoing requests, can be any string
    access_key: "<your key here>"
    ooc_bridge:
      enabled: true
      # ID of the Discord channel where OOC messages will be posted
      discord_channel_id: "1283485860968534066"

